This is my fourth and final portfolio submission, it is based on ML4DA Week 9 Part 3 "Creating your own models".

First of all, the initial step.

Step 1. Setting things up, initialising, importing libraries and assigning aliases to them.
Step 2. Loading the data

I start by improting all the necessary dependencies and libraries before assigning some of them industry standard aliases (ensures ease of understanding for external reviewers and follows best practice).

I chose Matplotlib over Seaborn as I am certain it is compatible with this version of TensorFlow and irregardles Seaborn is built on top of Matplotlib (though the visualised data would look better if I chosen Seaborn, in the event it was compatibe with my tf and python version).

I also loaded in the data that the model will be trained on and used the head() method to print the first 5 rows of the CSV to ensure data hygeine (no corrupted or missing values).

Since there are new technologies being used I will describe them. Tensorflow is an open-source framework for ML using data flow graphs. The nodes within the graph are represntative of mathematical operations and the graph edges represent the multidimensional data arrays, called tensors, that flow between them. TF is heavily used by data scientists and gives the programmer control over parameters. It was developed by Google to help the development of ML models, mainly deep learning models by providing tools for building, training and cross platform deployment, it allows for easier model building as it has many levels of abrstraction (tf handles certain calculations and operations for the user). Keras is a high level API for building deep learning models and runs on top of tf (they are now shipped together), it is also good for quick development.

tf is more popular in industry, has keras built in, offers more features, and is more scalable so perhaps these were why it was chosen over Pytorch as it is a seperate libray without keras shipped with it.

Deep learning explanation:
DL is a subset of ML that is driven by multi-layered NNs (input layers, hidden layers, output layer) with design inspired by the structure of a human's brain (the original NN). DL is made up of algorithms that allow software to train itself to do tasks, like NLP and computer vision (image recognition). DL models power most cutting edge AI today like GenAI and self-driving cars.

In the code section Dense is a densely connected NN that inherits from layers (from keras.layers import Dense).

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
from keras.layers import Dense
from keras.models import Sequential

# Loading the dataset
fuelcon_data = pd.read_csv("FuelConsumption.csv")

fuelcon_data.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

Quick data sanity check to ensure no missing values. Sum up all the data entries that are empty (none are empty so all is well).

In [3]:
fuelcon_data.isnull().sum()

MODELYEAR                   0
MAKE                        0
MODEL                       0
VEHICLECLASS                0
ENGINESIZE                  0
CYLINDERS                   0
TRANSMISSION                0
FUELTYPE                    0
FUELCONSUMPTION_CITY        0
FUELCONSUMPTION_HWY         0
FUELCONSUMPTION_COMB        0
FUELCONSUMPTION_COMB_MPG    0
CO2EMISSIONS                0
dtype: int64

Step 3. Selecting Features and Target

Before beginning to build the model it is time to talk about neural network and advanced NN concepts, forward propagation is the core process in a neural network where input data passes through all the layers in a network from the input layer to the output layer and generates an output. The input data moves through every layer, input layer to hidden layer(s) to output layer, of the NN where each neuron adds bias, applies weighted sum and passes the result through an activation function and it also makes predictions. A neuron in this context is the basic unit that takes inputs, each neuron is governed by an activation function (sigmoid, tanh, softmax, etc.). Activation functions are necessary to remove linearity as forwardpropagation's "a=z" is a linear combination of inputs and weights as well as the bias, a is the output. The introduction of nonlinearity brought by the activation function is pivotal for enabling the network to learn more complex/intricate patterns. tanh gives better performance for multi-layer NNs than sigmoid but still suffered from the vanishing gradient problem before ReLU was introduced.

Since forwardpropagation is about predicting a single output/target or dependent variable based off of multiple features it is an example of regression (a supervised learning technique), forwardpropagation also shares the same equation as linear regression with y=mx+c or y=mx+b. M being the slope, y being the dependent variable, b being the intercept and x as the independent variable (y and x are also coordinates). It is supervised learning since there has to be labelled training data for it to predict an output/it needs to training data.

Backpropagation is about error/loss calculation, gradient calculation, and weight updates. In a supervised learning environment data is labnelled and also referred to as Ground Truyth (T), if y hat does not equal (!=) T then training is required. Backpropagation calculates the error E which is the difference between predicted (y hat) and actual values (T) and then uses the difference (the loss) to perform gradient descent on the biases and weights in the network. Backpropagation is a taining algorith that updates weights by minimising error.

With this explanation it is clear why I start with forwardpropagation as I have no loss if I have not built a predictor model, thus backpropagation cannot be done before forwardpropagation.
The specification stated that the model must predict vehicle CO2 emissions (target/dependent variable) from the Engine Size, Number of Cylinders and Combined Mileage (features), features/predictors/independent variables are the input variables used by the model for predictions, features are the individual measurable quantifiable characteristics or properties of a phenomenon being observed.

Only the specified fatures were selected from the csv and assigned to the "features" variable, any other ones would just add noise that would throw off the predictions. FUELCONSUMPTION_COMB (combined fuelcon for highways and cities) was chosen over FUELCONSUMPTION_COMB_MPG since mileage is the number of miles travelled during a car's lifetime whereas MPG is just how many miles you can go per gallon of fuel, what this means is that FUELCONSUMPTION_COMB gives us the total fuel used for the 2 types of roads the car was drivem on (highway and cities, at least the 2 types of roads that there are data for) and FUELCONSUMPTION_COMB_MPG just gives how many MPG. FUELCONSUMPTION_COMB_MPG does not say how many gallons of fuel were consumed in total as opposed to FUELCONSUMPTION_COMB saying how much fuel was consumed for a set distance on both road types. FUELCONSUMPTION_COMB is also directly proportional as fuel consumption goes up so do emissions, FUELCONSUMPTION_COMB_MPG seems less intuitive and less related.

In [4]:
# Predictors: Engine Size, Cylinders, Combined Mileage
features = fuelcon_data[['ENGINESIZE', 'CYLINDERS', 'FUELCONSUMPTION_COMB']]
target = fuelcon_data['CO2EMISSIONS'] # the target the model will predict

features.head() # display first 5 rows and check that the correct columns were selected

   ENGINESIZE  CYLINDERS  FUELCONSUMPTION_COMB
0         2.0          4                   8.5
1         2.4          4                   9.6
2         1.5          4                   5.9
3         3.5          6                  11.1
4         3.5          6                  10.6

Step 4. Normalisation of the data

I chose normalisation over scaling since I do not need to measure how far apart my data points are and I less so want to change the scale but more so want to ensure the data is normally distributed to minimise outliers.

I used Z-score normalisation, also known as standardisation since ML algorithms tend to struggle with datasets where features are on very different scales, if these features were not normalised the algorithm could potentialy give more importance to a feature with a larger scale, thus leading to inaccurate predictions. Mean and std calculations handled by pythonic abstractions.

I did not do a train test split here as week 8 said that was best practice for scaling (not sure if this was used inetrchangeably) and since the features selected are the only predictors there is no target leakage (like if it aleady knew CO2 emissions whilst trying to calculatet them), though an IBM states normalisation should be done on training data only the actual IBM Regression ipynb did not train test split so all should be fine (Classification did though). If this does lead to overfitting I will knwo it was due to not train/test splitting the data (80/20) before normalisation and will conclude it was bad practice.

In [5]:
# Neural networks perform significantly better when inputs are scaled
features_norm = (features - features.mean()) / features.std()
n_cols = features_norm.shape[1] # number of features/predictors

Step 5. Building a Neural Network and Compiling the model

Defined the function for the regression model. Sequential was used for the model since it is apt for a plain linear stack of layers. Not the best for multiple inputs allegedly.

"Dense(50, activation='relu')," means that there are 50 neurons with ReLU activation function, ReLU is used to remove linearity. Dense layers were used to ensure network interconnectivity where every neuron in the layer is connected to every neuron in the prior layer, this allows the deep learning models to learn complex patterns and relationships in data (ReLU allegedly makes networks sparse though). Softmax is not used in the output layer as this is not a classification model but a regression one. Sigmoid activation function is not used as it does not perform well with multi-layer NNs (as mentioned prior), and still suffers from vanishing gradient (not that much of a problem since I will not do backpropagation and instead use MAE to determine accuracy for predictions).

could also use leaky_relu instead of relu. Leaky ReLU handles ReLU limitations like dead neurons (if a neuron only gets negative inputs it outputs 0 and the gradient becomes 0 so it stops learning), faster learning than ReLU, and more. 

metrics='mae' added into the model.compile() method for a guage of accuracy of model predictions. input_shape used to say that I want the same amount of features as inputs for the input layer a.k.a I want a starting shape of 3, "model.add(Dense(1))" the 1 denotes one node/neuron as the output for the Output layer since linear regression predicts one output/dependent variable based off of multiple inputs/independent variables/X where X is a feature matrix.

input_shape allwos that variable to be automatically adjusted if I add more features later as opposed to manually specifying the amount of inputs I want.

optimizer='adam' ,eans automatically adjust the learning rate as training progresses (this optimiser is stochastic), loss='mean_squared_error' means square the loss actually (amendment to any erroneuos mention of using MAE as loss), mae (the average of the difference bewteen actual and predicted value) is used as a metric for the metrics class and just reports how far off the predictions are and serve as an accuracy metric/guide.

In [6]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(50, activation='leaky_relu', input_shape=(n_cols,))) # input layer
    # hidden layers
    model.add(Dense(25, activation='leaky_relu'))
    model.add(Dense(25, activation='leaky_relu'))
    model.add(Dense(25, activation='leaky_relu'))
    model.add(Dense(25, activation='leaky_relu'))

    # output layer
    model.add(Dense(1))
    
    # compilng the model
    model.compile(optimizer='adam', loss='mean_squared_error', metrics='mae')
    return model

Step 6. Training and testing the network

There is a split here as was shown in the Regression with Keras ipynb, meaning since some data is held as a testing/validation set here that there should not be an issue with my standardising earlier. fit() is used to train the model, it is not unique to scikit-learn.

An epoch is one full pass through the entire training dataset where every data sample (a single instance or observation within a dataset, it represents a unit of data collected for data anlysis or modeling) is passed through the model and its parameters are updated based on the calculated error. Since the current training data is 70% then the batch it is running on should be 70% of the original training dataset.

Message that the training is complete at the end to inform people. New line taken to make it more obvious.

In [ ]:
# build the model using the function call
model = regression_model()

# fit the model
model.fit(features_norm, target, validation_split=0.3, epochs=100, verbose=2) # assigned the value of this method to the history variable for future plot
print("\n-Training complete")

Epoch 1/100
24/24 - 1s - loss: 72649.5156 - mae: 261.8951 - val_loss: 62332.0078 - val_mae: 242.3593 - 733ms/epoch - 31ms/step
Epoch 2/100
24/24 - 0s - loss: 71927.8047 - mae: 260.7028 - val_loss: 61257.6211 - val_mae: 240.4420 - 59ms/epoch - 2ms/step
Epoch 3/100
24/24 - 0s - loss: 67804.0859 - mae: 253.8112 - val_loss: 55197.3828 - val_mae: 229.2809 - 61ms/epoch - 3ms/step
Epoch 4/100
24/24 - 0s - loss: 49074.9922 - mae: 215.9789 - val_loss: 31275.1621 - val_mae: 170.7784 - 60ms/epoch - 3ms/step
Epoch 5/100
24/24 - 0s - loss: 18073.0586 - mae: 118.6162 - val_loss: 11876.4727 - val_mae: 87.9343 - 60ms/epoch - 3ms/step
Epoch 6/100
24/24 - 0s - loss: 9065.2080 - mae: 76.4487 - val_loss: 8935.7979 - val_mae: 80.1666 - 60ms/epoch - 3ms/step
Epoch 7/100
24/24 - 0s - loss: 6584.2393 - mae: 66.7007 - val_loss: 6362.7314 - val_mae: 65.9369 - 59ms/epoch - 2ms/step
Epoch 8/100
24/24 - 0s - loss: 4735.3936 - mae: 56.1487 - val_loss: 4604.8013 - val_mae: 56.1372 - 61ms/epoch - 3ms/step
Epoch 9/100
24/24 - 0s - loss: 3338.2185 - mae: 46.9680 - val_loss: 3289.3691 - val_mae: 47.5075 - 60ms/epoch - 3ms/step
Epoch 10/100
24/24 - 0s - loss: 2325.9092 - mae: 39.5103 - val_loss: 2350.1453 - val_mae: 40.0522 - 60ms/epoch - 3ms/step
Epoch 11/100
24/24 - 0s - loss: 1669.1736 - mae: 33.8574 - val_loss: 1691.2484 - val_mae: 33.6330 - 60ms/epoch - 3ms/step
Epoch 12/100
24/24 - 0s - loss: 1230.7942 - mae: 29.3299 - val_loss: 1224.6536 - val_mae: 27.6661 - 59ms/epoch - 2ms/step
Epoch 13/100
24/24 - 0s - loss: 956.1259 - mae: 25.2203 - val_loss: 944.1275 - val_mae: 23.4858 - 67ms/epoch - 3ms/step
Epoch 14/100
24/24 - 0s - loss: 821.8208 - mae: 22.8126 - val_loss: 780.9040 - val_mae: 20.7628 - 62ms/epoch - 3ms/step
Epoch 15/100
24/24 - 0s - loss: 742.2513 - mae: 21.2315 - val_loss: 665.5054 - val_mae: 18.8675 - 60ms/epoch - 3ms/step
Epoch 16/100
24/24 - 0s - loss: 695.7929 - mae: 20.3046 - val_loss: 609.7107 - val_mae: 17.8880 - 60ms/epoch - 3ms/step
Epoch 17/100
24/24 - 0s - loss: 661.5892 - mae: 19.5841 - val_loss: 584.0814 - val_mae: 17.3388 - 59ms/epoch - 2ms/step
Epoch 18/100
24/24 - 0s - loss: 664.1782 - mae: 19.4492 - val_loss: 566.8190 - val_mae: 16.9480 - 59ms/epoch - 2ms/step
Epoch 19/100
24/24 - 0s - loss: 617.8042 - mae: 18.5613 - val_loss: 487.6805 - val_mae: 16.1577 - 90ms/epoch - 4ms/step
Epoch 20/100
24/24 - 0s - loss: 643.1193 - mae: 18.8352 - val_loss: 453.3540 - val_mae: 15.4366 - 61ms/epoch - 3ms/step
Epoch 21/100
24/24 - 0s - loss: 592.0894 - mae: 17.9221 - val_loss: 429.2694 - val_mae: 15.1919 - 59ms/epoch - 2ms/step
Epoch 22/100
24/24 - 0s - loss: 581.7750 - mae: 17.7693 - val_loss: 408.1820 - val_mae: 14.7438 - 58ms/epoch - 2ms/step
Epoch 23/100
24/24 - 0s - loss: 574.8587 - mae: 17.5074 - val_loss: 395.1483 - val_mae: 14.4078 - 59ms/epoch - 2ms/step
Epoch 24/100
24/24 - 0s - loss: 549.5069 - mae: 16.9890 - val_loss: 384.8896 - val_mae: 14.1354 - 59ms/epoch - 2ms/step
Epoch 25/100
24/24 - 0s - loss: 539.9600 - mae: 16.8138 - val_loss: 409.2431 - val_mae: 14.2049 - 59ms/epoch - 2ms/step
Epoch 26/100
24/24 - 0s - loss: 535.5316 - mae: 16.5802 - val_loss: 357.7820 - val_mae: 13.7582 - 58ms/epoch - 2ms/step
Epoch 27/100
24/24 - 0s - loss: 536.8459 - mae: 16.5290 - val_loss: 342.7394 - val_mae: 13.5470 - 58ms/epoch - 2ms/step
Epoch 28/100
24/24 - 0s - loss: 516.0065 - mae: 15.9428 - val_loss: 331.7811 - val_mae: 13.0736 - 91ms/epoch - 4ms/step
Epoch 29/100
24/24 - 0s - loss: 509.0106 - mae: 15.7597 - val_loss: 349.2458 - val_mae: 13.1514 - 60ms/epoch - 2ms/step
Epoch 30/100
24/24 - 0s - loss: 504.8466 - mae: 15.7311 - val_loss: 333.8350 - val_mae: 12.7687 - 63ms/epoch - 3ms/step
Epoch 31/100
24/24 - 0s - loss: 507.2620 - mae: 15.6123 - val_loss: 325.7901 - val_mae: 13.2666 - 62ms/epoch - 3ms/step
Epoch 32/100
24/24 - 0s - loss: 494.4394 - mae: 15.3178 - val_loss: 296.1873 - val_mae: 12.5403 - 64ms/epoch - 3ms/step
Epoch 33/100
24/24 - 0s - loss: 490.2818 - mae: 15.1882 - val_loss: 293.9078 - val_mae: 12.2066 - 65ms/epoch - 3ms/step
Epoch 34/100
24/24 - 0s - loss: 476.1863 - mae: 14.8386 - val_loss: 320.8399 - val_mae: 12.2966 - 63ms/epoch - 3ms/step
Epoch 35/100
24/24 - 0s - loss: 479.6387 - mae: 14.6664 - val_loss: 290.4259 - val_mae: 11.8992 - 60ms/epoch - 3ms/step
Epoch 36/100
24/24 - 0s - loss: 469.4846 - mae: 14.5356 - val_loss: 287.8727 - val_mae: 11.8725 - 59ms/epoch - 2ms/step
Epoch 37/100
24/24 - 0s - loss: 462.5211 - mae: 14.5288 - val_loss: 278.7386 - val_mae: 11.6169 - 60ms/epoch - 3ms/step
Epoch 38/100
24/24 - 0s - loss: 459.5169 - mae: 14.1059 - val_loss: 265.3405 - val_mae: 11.0786 - 61ms/epoch - 3ms/step
Epoch 39/100
24/24 - 0s - loss: 459.4903 - mae: 13.8899 - val_loss: 276.4623 - val_mae: 11.9805 - 59ms/epoch - 2ms/step
Epoch 40/100
24/24 - 0s - loss: 466.2978 - mae: 14.1299 - val_loss: 254.5831 - val_mae: 10.7936 - 59ms/epoch - 2ms/step
Epoch 41/100
24/24 - 0s - loss: 439.4936 - mae: 13.3721 - val_loss: 261.0689 - val_mae: 10.6098 - 59ms/epoch - 2ms/step
Epoch 42/100
24/24 - 0s - loss: 439.3444 - mae: 13.2849 - val_loss: 236.7242 - val_mae: 10.6811 - 60ms/epoch - 3ms/step
Epoch 43/100
24/24 - 0s - loss: 436.9461 - mae: 13.1975 - val_loss: 237.7241 - val_mae: 10.3545 - 59ms/epoch - 2ms/step
Epoch 44/100
24/24 - 0s - loss: 447.1839 - mae: 13.1638 - val_loss: 239.8631 - val_mae: 9.9607 - 59ms/epoch - 2ms/step
Epoch 45/100
24/24 - 0s - loss: 427.3204 - mae: 12.8162 - val_loss: 228.3696 - val_mae: 10.3466 - 72ms/epoch - 3ms/step
Epoch 46/100
24/24 - 0s - loss: 433.5175 - mae: 12.9391 - val_loss: 218.5158 - val_mae: 10.6424 - 61ms/epoch - 3ms/step
Epoch 47/100
24/24 - 0s - loss: 422.2053 - mae: 12.8630 - val_loss: 218.2052 - val_mae: 10.5571 - 60ms/epoch - 3ms/step
Epoch 48/100
24/24 - 0s - loss: 409.2602 - mae: 12.4149 - val_loss: 211.3761 - val_mae: 9.9277 - 61ms/epoch - 3ms/step
Epoch 49/100
24/24 - 0s - loss: 424.6066 - mae: 12.3270 - val_loss: 237.1836 - val_mae: 9.1716 - 60ms/epoch - 3ms/step
Epoch 50/100
24/24 - 0s - loss: 403.3155 - mae: 11.9290 - val_loss: 212.9458 - val_mae: 9.8498 - 61ms/epoch - 3ms/step
Epoch 51/100
24/24 - 0s - loss: 415.2561 - mae: 12.3261 - val_loss: 218.2396 - val_mae: 9.9236 - 62ms/epoch - 3ms/step
Epoch 52/100
24/24 - 0s - loss: 409.9658 - mae: 12.1617 - val_loss: 218.4241 - val_mae: 9.0660 - 61ms/epoch - 3ms/step
Epoch 53/100
24/24 - 0s - loss: 401.2569 - mae: 11.7854 - val_loss: 205.4201 - val_mae: 9.4384 - 59ms/epoch - 2ms/step
Epoch 54/100
24/24 - 0s - loss: 391.3162 - mae: 11.6913 - val_loss: 189.9428 - val_mae: 9.3168 - 60ms/epoch - 3ms/step
Epoch 55/100
24/24 - 0s - loss: 380.7050 - mae: 11.1069 - val_loss: 185.3541 - val_mae: 8.8336 - 60ms/epoch - 3ms/step
Epoch 56/100
24/24 - 0s - loss: 391.3263 - mae: 11.4452 - val_loss: 186.4422 - val_mae: 8.8057 - 60ms/epoch - 3ms/step
Epoch 57/100
24/24 - 0s - loss: 381.6191 - mae: 11.0509 - val_loss: 275.9599 - val_mae: 10.0996 - 61ms/epoch - 3ms/step
Epoch 58/100
24/24 - 0s - loss: 386.9335 - mae: 11.4662 - val_loss: 203.6733 - val_mae: 8.6660 - 63ms/epoch - 3ms/step
Epoch 59/100
24/24 - 0s - loss: 370.0824 - mae: 11.0745 - val_loss: 211.7841 - val_mae: 8.1833 - 59ms/epoch - 2ms/step
Epoch 60/100
24/24 - 0s - loss: 377.6212 - mae: 11.0805 - val_loss: 191.1142 - val_mae: 8.2861 - 58ms/epoch - 2ms/step
Epoch 61/100
24/24 - 0s - loss: 363.4057 - mae: 10.5664 - val_loss: 183.7838 - val_mae: 8.0244 - 59ms/epoch - 2ms/step
Epoch 62/100
24/24 - 0s - loss: 382.2848 - mae: 10.9010 - val_loss: 178.7791 - val_mae: 7.9481 - 60ms/epoch - 3ms/step
Epoch 63/100
24/24 - 0s - loss: 367.9478 - mae: 10.8705 - val_loss: 177.5682 - val_mae: 8.5994 - 64ms/epoch - 3ms/step
Epoch 64/100
24/24 - 0s - loss: 384.2955 - mae: 10.9672 - val_loss: 201.2094 - val_mae: 7.8250 - 60ms/epoch - 3ms/step
Epoch 65/100
24/24 - 0s - loss: 368.5346 - mae: 10.9248 - val_loss: 198.6154 - val_mae: 7.8307 - 60ms/epoch - 3ms/step
Epoch 66/100
24/24 - 0s - loss: 359.5753 - mae: 10.3746 - val_loss: 191.9651 - val_mae: 8.0862 - 61ms/epoch - 3ms/step
Epoch 67/100
24/24 - 0s - loss: 361.3889 - mae: 10.5783 - val_loss: 173.9771 - val_mae: 8.0953 - 61ms/epoch - 3ms/step
Epoch 68/100
24/24 - 0s - loss: 354.3114 - mae: 10.1869 - val_loss: 180.2797 - val_mae: 7.5281 - 63ms/epoch - 3ms/step
Epoch 69/100
24/24 - 0s - loss: 354.0437 - mae: 10.3012 - val_loss: 185.2388 - val_mae: 7.6050 - 59ms/epoch - 2ms/step
Epoch 70/100
24/24 - 0s - loss: 360.9328 - mae: 10.2747 - val_loss: 166.6235 - val_mae: 7.7679 - 66ms/epoch - 3ms/step
Epoch 71/100
24/24 - 0s - loss: 357.8752 - mae: 10.3419 - val_loss: 209.7168 - val_mae: 7.9042 - 60ms/epoch - 3ms/step
Epoch 72/100
24/24 - 0s - loss: 355.3148 - mae: 10.6745 - val_loss: 171.8616 - val_mae: 7.9049 - 60ms/epoch - 3ms/step
Epoch 73/100
24/24 - 0s - loss: 354.3689 - mae: 10.4906 - val_loss: 171.4291 - val_mae: 9.3194 - 89ms/epoch - 4ms/step
Epoch 74/100
24/24 - 0s - loss: 357.2743 - mae: 10.4021 - val_loss: 209.5569 - val_mae: 8.2716 - 58ms/epoch - 2ms/step
Epoch 75/100
24/24 - 0s - loss: 348.8818 - mae: 10.1305 - val_loss: 168.0661 - val_mae: 7.7222 - 59ms/epoch - 2ms/step
Epoch 76/100
24/24 - 0s - loss: 348.3664 - mae: 10.1193 - val_loss: 227.1763 - val_mae: 8.9664 - 60ms/epoch - 2ms/step
Epoch 77/100
24/24 - 0s - loss: 356.6935 - mae: 10.5069 - val_loss: 172.3373 - val_mae: 7.6337 - 59ms/epoch - 2ms/step
Epoch 78/100
24/24 - 0s - loss: 355.6784 - mae: 10.2811 - val_loss: 160.2978 - val_mae: 8.5524 - 59ms/epoch - 2ms/step
Epoch 79/100
24/24 - 0s - loss: 355.3513 - mae: 10.2235 - val_loss: 183.4696 - val_mae: 7.3369 - 66ms/epoch - 3ms/step
Epoch 80/100
24/24 - 0s - loss: 359.7277 - mae: 10.4148 - val_loss: 204.0426 - val_mae: 7.9143 - 62ms/epoch - 3ms/step
Epoch 81/100
24/24 - 0s - loss: 350.2779 - mae: 10.4284 - val_loss: 176.6548 - val_mae: 7.9584 - 61ms/epoch - 3ms/step
Epoch 82/100
24/24 - 0s - loss: 352.0175 - mae: 9.9360 - val_loss: 189.1288 - val_mae: 7.4695 - 59ms/epoch - 2ms/step
Epoch 83/100
24/24 - 0s - loss: 347.1261 - mae: 9.8818 - val_loss: 161.9384 - val_mae: 8.8373 - 60ms/epoch - 3ms/step
Epoch 84/100
24/24 - 0s - loss: 347.2880 - mae: 10.2346 - val_loss: 168.7330 - val_mae: 8.0138 - 59ms/epoch - 2ms/step
Epoch 85/100
24/24 - 0s - loss: 344.8701 - mae: 9.6356 - val_loss: 195.7578 - val_mae: 7.8568 - 59ms/epoch - 2ms/step
Epoch 86/100
24/24 - 0s - loss: 355.0254 - mae: 10.0320 - val_loss: 164.3327 - val_mae: 7.6159 - 65ms/epoch - 3ms/step
Epoch 87/100
24/24 - 0s - loss: 346.8283 - mae: 9.9872 - val_loss: 157.7131 - val_mae: 7.4022 - 69ms/epoch - 3ms/step
Epoch 88/100
24/24 - 0s - loss: 339.7304 - mae: 9.3853 - val_loss: 164.0201 - val_mae: 7.2167 - 75ms/epoch - 3ms/step
Epoch 89/100
24/24 - 0s - loss: 345.0361 - mae: 10.1183 - val_loss: 205.2460 - val_mae: 8.0131 - 73ms/epoch - 3ms/step
Epoch 90/100
24/24 - 0s - loss: 342.3653 - mae: 10.0999 - val_loss: 172.0736 - val_mae: 7.2675 - 60ms/epoch - 3ms/step
Epoch 91/100
24/24 - 0s - loss: 340.3250 - mae: 9.4341 - val_loss: 188.5445 - val_mae: 7.4470 - 58ms/epoch - 2ms/step
Epoch 92/100
24/24 - 0s - loss: 351.1484 - mae: 9.8859 - val_loss: 165.7316 - val_mae: 7.3393 - 58ms/epoch - 2ms/step
Epoch 93/100
24/24 - 0s - loss: 340.9114 - mae: 9.7579 - val_loss: 171.3144 - val_mae: 7.4599 - 61ms/epoch - 3ms/step
Epoch 94/100
24/24 - 0s - loss: 351.2375 - mae: 10.1620 - val_loss: 179.5119 - val_mae: 7.5078 - 73ms/epoch - 3ms/step
Epoch 95/100
24/24 - 0s - loss: 348.7639 - mae: 9.8322 - val_loss: 183.0301 - val_mae: 7.4697 - 73ms/epoch - 3ms/step
Epoch 96/100
24/24 - 0s - loss: 351.5415 - mae: 10.3296 - val_loss: 154.7338 - val_mae: 7.3111 - 61ms/epoch - 3ms/step
Epoch 97/100
24/24 - 0s - loss: 340.6834 - mae: 9.6553 - val_loss: 154.5155 - val_mae: 7.8080 - 59ms/epoch - 2ms/step
Epoch 98/100
24/24 - 0s - loss: 347.3329 - mae: 9.7880 - val_loss: 177.9460 - val_mae: 7.3276 - 60ms/epoch - 3ms/step
Epoch 99/100
24/24 - 0s - loss: 333.6469 - mae: 9.6596 - val_loss: 191.6818 - val_mae: 8.1392 - 59ms/epoch - 2ms/step
Epoch 100/100
24/24 - 0s - loss: 342.3412 - mae: 9.9362 - val_loss: 164.1878 - val_mae: 7.5676 - 60ms/epoch - 3ms/step

-Training complete

Step 7. Experimentation

I will run expirements where I change at least these three things and then log my findings here:

1.  Increase or decreate number of neurons in hidden layers

Decreasing the amount of neurons in the hidden layer from 50 to 10 increases loss/error and MAE slightly
Increasing the amount of neurons in the hidden layer from 10 to 500 noticeably decreased loss and slightly decreased MAE on the first epoch, it then proceeded to get better but by the 100th epoch it became worse than my initial neuron value of 50 as val_loss rose by a lot and MAE increased.

2.  Add more hidden layers

I initially only had one but I will add 3 more hidden layers, each with 25 neurons (if they did not have the same amount of neurons one or some nodes would not be connected and would be sparser, meaning less understanding of complex patterns, this is not ideal since my dataset is not large enough for sparse NNs to be computationally better than dense ones), and document my finding.

I saw an initial increase in loss and MAE but then I saw a greater decrease as compared to only having one hidden layer, more layers mean more calculations before the final prediction, thus more accuracy. A lower MAE and loss means more accuracy too, if it is too low (perfect case of 0) then it is most likely overfitted. 

3.  Increase number of epochs

I increased the number of epochs to 300 from 100, this increased the run time from a few seconds to 20 seconds (rounded from 19.8) but the final epoch's loss was 280 from 417 anmd the mae was 8.22 from 30.53 thus it improved the model accuracy the most. Decreasing epochs would have the inverse effect. This shows that epochs do update the model as each iteration processes a batchm finds loss and then adjusts its weights and parameteers based off of that loss.


4. bonus experiment, Since I am not using backpropagation I will not permanently change the compile() method's optimiser to sgd as I am not using gradient descent to verify accurcay. I will experiment with it now to see what happens. All it did was corrput my values and make them "nan"


5.  Change activation functions

relu changed to leaky_relu

This initially brought positive changes but by the 300th epoch loss was down by 6 units, mae was up by around 0.7 and val_mae was up by around 0.13. Albeit val_loss was down by ~ 29 units.


Misc:
A verbose of 0 shows nothing, 1 shows an animated progress bar with dots (...) and === symbols, 2 just mentions the epochs.

Step 8. Plot val_mae and MAE

This part makes use of matplotlib for more data visualisation for visual feedback as this is important in industry since many people are visual learners, and there is a focus on building dashboards and other visual things.

The kernel keeps crashing and I could not fix it in time, I suspect this is due to a version conflict with tf and python 3, even when I tried to do the earliest week's extension installing tf through conda navigator did not work as I chose a modern Python version that tf did not support (not yet I assume). If it did work I would have shown a plot of the validation mae and the actual mae to see how accurate the model is and whether the lines overlap or superimpose on one another. Either that or the equivalent but with loss as opposed to mae.

The last reference in this notebook shows the error page I was taken to after clicking a hyperlink here about why my kernel crashed.

In [ ]:
# did not work as intended

:

References:
https://www.geeksforgeeks.org/deep-learning/what-is-forward-propagation-in-neural-networks/
https://www.datacamp.com/tutorial/forward-propagation-neural-networks
https://www.geeksforgeeks.org/machine-learning/difference-between-back-propagation-and-feed-forward-neural-network/
https://www.geeksforgeeks.org/machine-learning/neural-networks-a-beginners-guide/
https://share.google/wF3hbvdb4n4CN65w6
https://www.geeksforgeeks.org/machine-learning/features-and-labels-in-supervised-learning-a-practical-approach/
https://www.geeksforgeeks.org/machine-learning/how-to-handle-noise-in-machine-learning/
https://www.nvidia.com/en-gb/glossary/tensorflow/
https://www.geeksforgeeks.org/python/introduction-to-tensorflow/
https://www.tensorflow.org/about
https://www.simplilearn.com/keras-vs-tensorflow-vs-pytorch-article
https://medium.com/@kanerika/keras-vs-pytorch-which-ml-framework-is-the-best-for-you-b3eb6451dd66
https://www.kaggle.com/code/alexisbcook/scaling-and-normalization
https://stats.stackexchange.com/questions/458579/should-i-normalize-all-data-prior-feeding-the-neural-network-models
https://www.geeksforgeeks.org/data-analysis/normalization-and-scaling/
https://www.geeksforgeeks.org/data-analysis/z-score-normalization-definition-and-examples/
https://h2o.ai/wiki/target-leakage/
https://www.ibm.com/think/topics/data-leakage-machine-learning
https://www.tensorflow.org/api_docs/python/tf/keras/utils/split_dataset
https://keras.io/guides/sequential_model/
https://www.geeksforgeeks.org/deep-learning/dense-layer-tf-keras-layers-dense-in-tensorflow/
https://www.geeksforgeeks.org/machine-learning/ml-classification-vs-regression/
https://www.geeksforgeeks.org/machine-learning/Leaky-Relu-Activation-Function-in-Deep-Learning/
https://www.geeksforgeeks.org/deep-learning/neural-network-node/
https://www.reddit.com/r/learnmachinelearning/comments/7uvdnr/x_y_is_feature_label_by_convention_in_machine/
https://keras.io/api/metrics/
https://keras.io/api/optimizers/adam/
https://www.ibm.com/think/topics/deep-learning
https://www.geeksforgeeks.org/machine-learning/epoch-in-machine-learning/
https://datascience.stackexchange.com/questions/56263/what-is-sample-and-feature
https://medium.com/@frankcool/data-samples-vs-features-in-machine-learning-b9d4b50c8fce
https://stackoverflow.com/questions/47902295/what-is-the-use-of-verbose-in-keras-while-validating-the-model
https://www.baeldung.com/cs/neural-networks-dense-sparse
https://en.wikipedia.org/wiki/NaN
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense
https://github.com/microsoft/vscode-jupyter/wiki/Kernel-crashes